#!/bin/bash
clear

# - Cores
RED='\033[1;31m'
YELLOW='\033[1;33m'
SCOLOR='\033[0m'

# - Funções
function verifica_root() {
    if [[ "$EUID" -ne 0 ]]; then
        echo -e "${RED}[x] VC PRECISA EXECUTAR COMO USUARIO ROOT!${SCOLOR}"
        exit 1
    fi
}

function verifica_arquitetura() {
    case "$(uname -m)" in
        'amd64' | 'x86_64')
            arch='64'
            ;;
        'aarch64' | 'armv8')
            arch='arm64'
            ;;
        *)
            echo -e "${RED}[x] ARQUITETURA INCOMPATIVEL!${SCOLOR}"
            exit 1
            ;;
    esac
}

function verifica_os() {
    if grep -qs "ubuntu" /etc/os-release; then
        os_version=$(grep 'VERSION_ID' /etc/os-release | cut -d '"' -f 2 | tr -d '.')
        if [[ "$os_version" -lt 1804 ]]; then
            echo -e "${RED}[x] VERSAO DO UBUNTU INCOMPATIVEL!\n${YELLOW}[!] REQUER UBUNTU 18.04 OU SUPERIOR!${SCOLOR}"
            exit 1
        fi
    elif [[ -e /etc/debian_version ]]; then
        os_version=$(grep -oE '[0-9]+' /etc/debian_version | head -1)
        if [[ "$os_version" -lt 9 ]]; then
            echo -e "${RED}[x] VERSAO DO DEBIAN INCOMPATIVEL!\n${YELLOW}[!] REQUER DEBIAN 9 OU SUPERIOR!${SCOLOR}"
            exit 1
        fi
    else
        echo -e "${RED}[x] OS INCOMPATIVEL!\n${YELLOW}[!] REQUER DISTROS BASE DEBIAN/UBUNTU!${SCOLOR}"
        exit 1
    fi
}

function atualiza_sistema() {
    dpkg --configure -a
    apt update -y && apt upgrade -y
    apt install unzip python3 -y
}

function desabilita_ipv6() {
    sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -p
    echo 'net.ipv6.conf.all.disable_ipv6 = 1' > /etc/sysctl.d/70-disable-ipv6.conf
    sysctl -p -f /etc/sysctl.d/70-disable-ipv6.conf
}

function executa_instalador() {
    [[ -e Plus ]] && rm Plus
    wget raw.githubusercontent.com/vmell0/sshpro/main/script/64/Plus && chmod 777 Plus && ./Plus
}

# - Execução
verifica_root
verifica_arquitetura
verifica_os
atualiza_sistema
desabilita_ipv6
executa_instalador
